source 'http://rubygems.org'
gem 'rubygems-update'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'dotenv'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'